name: Deploy Bot

on:
  push:
    branches: [main]
    paths:
      - 'bot/**'
      - '.github/workflows/deploy-bot.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # - uses: google-github-actions/setup-gcloud@v1
      #   with:
      #     project_id: ${{ secrets.GCP_PROJECT_ID }}
      #     service_account_key: ${{ secrets.GCP_SA_KEY }}
      # - run: gcloud --quiet auth configure-docker

      - name: Build image
        run: |
          cd bot
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.CLOUD_RUN_SERVICE }}:$GITHUB_SHA .

      - name: Push image
        run: docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.CLOUD_RUN_SERVICE }}:$GITHUB_SHA

      - name: Deploy
        run: |
          gcloud run deploy ${{ secrets.CLOUD_RUN_SERVICE }} \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.CLOUD_RUN_SERVICE }}:$GITHUB_SHA \
            --region ${{ secrets.CLOUD_RUN_REGION }} \
            --platform managed \
            --set-env-vars META_VERIFY_TOKEN=${{ secrets.META_VERIFY_TOKEN }},META_APP_SECRET=${{ secrets.META_APP_SECRET }},META_WA_PHONE_NUMBER_ID=${{ secrets.META_WA_PHONE_NUMBER_ID }},META_GRAPH_API_TOKEN=${{ secrets.META_GRAPH_API_TOKEN }},SUPABASE_URL=${{ secrets.SUPABASE_URL }},SUPABASE_SERVICE_ROLE=${{ secrets.SUPABASE_SERVICE_ROLE }},SUPABASE_BUCKET=lesson-media,ALLOWED_SENDERS=${{ secrets.ALLOWED_SENDERS }}

      # Alternative deployment targets (Fly.io/Render) can be added here.
